#!/bin/sh /etc/rc.common
# Copyright (C) 2025 jimmy

START=50
STOP=15

DESTDIR=/tmp/qiperf 
if test ! -e "$DESTDIR"; then
  ln -s /mnt/ubi0_6 ${DESTDIR}
fi

QIPERFD="qiperfd"
QIPERFD_BIN="${DESTDIR}/usr/sbin/$QIPERFD"

start() {
        export LD_LIBRARY_PATH=${DESTDIR}/usr/lib
        echo start $QIPERFD
        # commands to launch application
        $QIPERFD_BIN &
}

stop() {
        echo stop $QIPERFD
        # commands to kill application
        killall $QIPERFD
}

